services:
  postgres:
    image: postgres:18
    container_name: eunexia-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eunexia_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: eunexia-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
